### ISSUE TITLE
Пропал параметр

### ISSUE THREAD

**Issue by programmwriter** [shylskii/blog_platformV4#12]
https://github.com/shylskii/blog_platformV4/blob/a0edebde05d1038fd39463a4c0f8e1fb3d36f6d9/src/components/article/article.js#L53-L62
Функция не ждет параметра, а ниже по коду в неё передается article.favorited
название функций должно начинаться с глагола типа onLikeArticle
eslint редко ругается зря, он говорит как лучше писать к примеру вот так намного понятнее
```
if(article.favorited){
    blogService.like(slug)
    return
}
blogService.dislike(slug)
```

**Comment by shylskii** [comment]
исправлено
