### ISSUE TITLE
Должно быть проще

### ISSUE THREAD

**Issue by programmwriter** [shylskii/blog_platformV4#13]
https://github.com/shylskii/blog_platformV4/blob/a0edebde05d1038fd39463a4c0f8e1fb3d36f6d9/src/components/article/article.js#L30-L38
когда ты удалил артикль ты производишь переход на страницу всех артиклей, в том компоненте при загрузке всегда должен делаться запрос на получение артиклей и лоадинг тоже там должен срабатывать

**Comment by shylskii** [comment]
исправлено
