### ISSUE TITLE
Создание объекта заголовка и sessionStorage

### ISSUE THREAD

**Issue by programmwriter** [shylskii/blog_platformV4#2]
https://github.com/shylskii/blog_platformV4/blob/a0edebde05d1038fd39463a4c0f8e1fb3d36f6d9/src/components/app/app.js#L24

Объект заголовка должен создаваться в services
Работу с sessionStorage лучше вынести в отдельную функцию или класс с обработкой, чтобы в коде было видно только функцию типа getSessionToken а не sessionStorage.getItem('RealworldBlogToken')

**Comment by shylskii** [comment]
исправлено
