### ISSUE TITLE
Исправить

### ISSUE THREAD

**Issue by programmwriter** [shylskii/blog_platformV4#3]
https://github.com/shylskii/blog_platformV4/blob/a0edebde05d1038fd39463a4c0f8e1fb3d36f6d9/src/components/app/app.js#L25

(page - 1)*5 писать такое в параметре как то не тру, лучше сделать эти манипуляции в сервисе
писать названия заглушки в методе then тоже не тру, лучше ставить название сущности которую запрашиваешь, тоесть если артикли то articles 
getArticles(page , autorization)
    .then((articles) =>

**Comment by shylskii** [comment]
исправлено
