### ISSUE TITLE
Options и return

### ISSUE THREAD

**Issue by programmwriter** [shylskii/blog_platformV4#8]
https://github.com/shylskii/blog_platformV4/blob/a0edebde05d1038fd39463a4c0f8e1fb3d36f6d9/src/service/blog-service.js#L13-L19
общепринято и намного понятней читается когда ты создаешь внутри метода константу объекта options и потом передаешь его в параметр вместо создавать непосредственно в параметре, переделай во всех методах

и return лучше писать с новой строки

**Comment by shylskii** [comment]
исправлено
